name: Five-Minute-Schedule

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print current time
        run: echo "The current time is $(date)"
